# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import protobuf.roll_out_service_pb2 as roll__out__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in roll_out_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RollOutServiceStub(object):
    """RPC service for roll-outs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.performRollOut = channel.unary_unary(
                '/evolution_algorithms.RollOutService/performRollOut',
                request_serializer=roll__out__service__pb2.RollOutRequest.SerializeToString,
                response_deserializer=roll__out__service__pb2.RollOutResponse.FromString,
                _registered_method=True)


class RollOutServiceServicer(object):
    """RPC service for roll-outs.
    """

    def performRollOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RollOutServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'performRollOut': grpc.unary_unary_rpc_method_handler(
                    servicer.performRollOut,
                    request_deserializer=roll__out__service__pb2.RollOutRequest.FromString,
                    response_serializer=roll__out__service__pb2.RollOutResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'evolution_algorithms.RollOutService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('evolution_algorithms.RollOutService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RollOutService(object):
    """RPC service for roll-outs.
    """

    @staticmethod
    def performRollOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evolution_algorithms.RollOutService/performRollOut',
            roll__out__service__pb2.RollOutRequest.SerializeToString,
            roll__out__service__pb2.RollOutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ParameterSyncServiceStub(object):
    """RPC service for parameter synchronization.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.syncParameter = channel.unary_unary(
                '/evolution_algorithms.ParameterSyncService/syncParameter',
                request_serializer=roll__out__service__pb2.ParamSyncRequest.SerializeToString,
                response_deserializer=roll__out__service__pb2.ParamSyncResponse.FromString,
                _registered_method=True)


class ParameterSyncServiceServicer(object):
    """RPC service for parameter synchronization.
    """

    def syncParameter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParameterSyncServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'syncParameter': grpc.unary_unary_rpc_method_handler(
                    servicer.syncParameter,
                    request_deserializer=roll__out__service__pb2.ParamSyncRequest.FromString,
                    response_serializer=roll__out__service__pb2.ParamSyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'evolution_algorithms.ParameterSyncService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('evolution_algorithms.ParameterSyncService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ParameterSyncService(object):
    """RPC service for parameter synchronization.
    """

    @staticmethod
    def syncParameter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evolution_algorithms.ParameterSyncService/syncParameter',
            roll__out__service__pb2.ParamSyncRequest.SerializeToString,
            roll__out__service__pb2.ParamSyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
